const componetData: componetDataType[] = [
  {
    title: "基础组件1",
    componentList: [
      {
        type: "ElInput",
        name: "输入框",
        icon: "",
        componentContent: {
          InputType: "text",
          variateName: "",
          defaultValue: "",
          width: "",
          size: "small",
          label: "输入框",
          labelWidth: "auto",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "ElInput",
        name: "文本域",
        icon: "",
        componentContent: {
          InputType: "textarea",
          variateName: "",
          defaultValue: "",
          width: "",
          size: "small",
          label: "输入框",
          labelWidth: "auto",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "ElRadio",
        name: "单选框",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "small",
          label: "输入框",
          labelWidth: "auto",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "ElCheckBox",
        name: "多选框",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "small",
          label: "输入框",
          labelWidth: "auto",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "ElSelect",
        name: "下拉选项",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "small",
          label: "输入框",
          labelWidth: "auto",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "ElDate",
        name: "时间选择器",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "small",
          label: "输入框",
          labelWidth: "auto",
          placeholder: "请输入",
          prop: "",
        },
      },
    ],
  },
  {
    title: "基础组件",
    componentList: [
      {
        type: "ElInput",
        name: "输入框",
        icon: "",
      },
      {
        type: "ElTextArea",
        name: "文本域",
        icon: "",
      },
      {
        type: "ElRadio",
        name: "单选框",
        icon: "",
      },
      {
        type: "ElCheckBox",
        name: "多选框",
        icon: "",
      },
      {
        type: "ElSelect",
        name: "下拉选项",
        icon: "",
      },
      {
        type: "ElDate",
        name: "时间选择器",
        icon: "",
      },
    ],
  },
];
export default componetData;
