const componetData: componetDataType[] = [
  {
    title: "基础组件1",
    componentList: [
      {
        type: "JInput",
        name: "输入框",
        icon: "",
        componentContent: {
          InputType: "text",
          variateName: "",
          defaultValue: "1",
          width: "",
          size: "default",
          label: "输入框",
          labelWidth: 0,
          labelPosition: "left",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "JInput",
        name: "文本域",
        icon: "",
        componentContent: {
          InputType: "textarea",
          variateName: "",
          defaultValue: "",
          width: "",
          size: "default",
          label: "输入框",
          labelWidth: 0,
          labelPosition: "left",
          placeholder: "请输入",
          prop: "",
        },
      },
      {
        type: "JRadio",
        name: "单选框",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "default",
          label: "输入框",
          labelWidth: 0,
          labelPosition: "left",
          placeholder: "请输入",
          prop: "",
          options: [
            {
              label: "选项一",
              value: 1,
            },
            {
              label: "选项二",
              value: 2,
            },
          ],
        },
      },
      {
        type: "JCheckBox",
        name: "多选框",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "default",
          label: "输入框",
          labelWidth: 0,
          labelPosition: "left",
          placeholder: "请输入",
          prop: "",
          options: [
            {
              label: "选项一",
              value: 1,
            },
            {
              label: "选项二",
              value: 2,
            },
          ],
        },
      },
      {
        type: "JSelect",
        name: "下拉选项",
        icon: "",
        componentContent: {
          variateName: "",
          defaultValue: "",
          width: "",
          size: "default",
          label: "输入框",
          labelWidth: 0,
          labelPosition: "left",
          placeholder: "请输入",
          prop: "",
          options: [
            {
              label: "选项一",
              value: 1,
            },
            {
              label: "选项二",
              value: 2,
            },
          ],
        },
      },
      // {
      //   type: "ElDate",
      //   name: "时间选择器",
      //   icon: "",
      //   componentContent: {
      //     variateName: "",
      //     defaultValue: "",
      //     width: "",
      //     size: "default",
      //     label: "输入框",
      //     labelWidth: "auto",
      //     placeholder: "请输入",
      //     prop: "",
      //   },
      // },
    ],
  },
];
export default componetData;
