import { defineStore } from "pinia";
import type { componentContentType } from "@/interface/component";
export default defineStore("appStore", {
  state: () => {
    return {
      AppData: {
        size: "default",
        labelPosition: "left",
        labelWidth: 0,
        formName: "formSetting",
        RefFormName: "formRef",
        rulesName: "rules",
        isDisabled: false,
        AppList: [],
      },
      currentComponent: {
        type: "JInput",
        name: "输入框",
        icon: "",
        uid: "",
        componentContent: {
          InputType: "text",
          variateName: "",
          defaultValue: "",
          width: "",
          size: "",
          label: "输入框",
          labelWidth: 0,
          labelPosition: "left",
          placeholder: "请输入",
          prop: "",
        } as componentContentType,
      },
      templateList: [
        {
          tempName: "模板一（个人简介）",
          tempInfo: {
            size: "default",
            labelPosition: "right",
            labelWidth: 82,
            formName: "formSetting",
            RefFormName: "formRef",
            rulesName: "rules",
            isDisabled: false,
            AppList: [
              {
                type: "JInput",
                name: "输入框",
                icon: "",
                componentContent: {
                  InputType: "text",
                  slotName: "",
                  slotContent: "",
                  suffixIcon: "",
                  prefixIcon: "Search",
                  maxLength: "10",
                  minLength: "",
                  showWordLimit: true,
                  clearable: true,
                  showPassword: false,
                  resize: "horizontal",
                  rows: 4,
                  variateName: "name",
                  defaultValue: "",
                  width: "",
                  size: "",
                  label: "姓名：",
                  labelWidth: 0,
                  labelPosition: "left",
                  placeholder: "请输入姓名",
                  prop: "",
                  isRequired: true,
                  disabled: false,
                  verifyMsg: "请输入姓名",
                  isCustomVerify: false,
                  customVerify: "",
                },
                uid: 1718084155576,
              },
              {
                type: "JInput",
                name: "输入框",
                icon: "",
                componentContent: {
                  InputType: "text",
                  slotName: "prepend",
                  slotContent: "+86",
                  suffixIcon: "",
                  prefixIcon: "",
                  maxLength: "11",
                  minLength: "",
                  showWordLimit: true,
                  clearable: true,
                  showPassword: false,
                  resize: "horizontal",
                  rows: 4,
                  variateName: "phone",
                  defaultValue: "",
                  width: "",
                  size: "",
                  label: "手机号：",
                  labelWidth: 0,
                  labelPosition: "left",
                  placeholder: "请输入手机号",
                  prop: "",
                  isRequired: true,
                  disabled: false,
                  verifyMsg: "请输入手机号",
                  isCustomVerify: true,
                  customVerify:
                    'const phoneRule = (rule, value, callback) => {\r\n    if(!value){\r\n        return callback(new Error("请输入手机号"))\r\n    }\r\n    if (!/^1(3[0-9]|5[0-3,5-9]|7[1-3,5-8]|8[0-9])\\d{8}$/.test(value)){\r\n        return callback(new Error("请输入正确格式的手机号！"));\r\n    }\r\n    callback();\r\n}\r\n\r\n',
                },
                uid: 1718084716558,
              },
              {
                type: "JSelect",
                name: "下拉选项",
                icon: "",
                componentContent: {
                  variateName: "education",
                  defaultValue: [],
                  width: "",
                  size: "",
                  label: "学历：",
                  labelWidth: 0,
                  labelPosition: "left",
                  clearable: true,
                  multiple: true,
                  collapseTags: true,
                  collapseTagsTooltip: true,
                  multipleLimit: 3,
                  effect: "light",
                  filterable: true,
                  placeholder: "请选择",
                  prop: "",
                  isRequired: true,
                  disabled: false,
                  verifyMsg: "请选择学历",
                  customVerify: "",
                  options: [
                    { label: "小学", value: 1 },
                    { label: "初中", value: 2 },
                    { label: "高中", value: 3 },
                    { label: "大学", value: 4 },
                  ],
                },
                uid: 1718091018010,
              },
              {
                type: "JRadio",
                name: "单选框",
                icon: "",
                componentContent: {
                  radioType: "button",
                  variateName: "age",
                  defaultValue: "",
                  width: "",
                  size: "default",
                  label: "性别：",
                  labelWidth: 0,
                  labelPosition: "left",
                  border: false,
                  textColor: "#ffffff",
                  fill: "#409EFF",
                  prop: "",
                  isRequired: true,
                  disabled: false,
                  verifyMsg: "请选择性别",
                  isCustomVerify: false,
                  customVerify: "",
                  options: [
                    { label: "男", value: 1 },
                    { label: "女", value: 2 },
                  ],
                },
                uid: 1718084162199,
              },
              {
                type: "JCheckBox",
                name: "多选框",
                icon: "",
                componentContent: {
                  checkBoxType: "checkbox",
                  variateName: "like",
                  defaultValue: [],
                  width: "",
                  size: "default",
                  label: "爱好：",
                  labelWidth: 0,
                  labelPosition: "left",
                  border: true,
                  min: 0,
                  max: 2,
                  textColor: "#ffffff",
                  fill: "#409eff",
                  placeholder: "请输入",
                  prop: "",
                  isRequired: true,
                  disabled: false,
                  verifyMsg: "请选择爱好",
                  customVerify: "",
                  options: [
                    { label: "足球", value: 1 },
                    { label: "篮球", value: 2 },
                    { label: "乒乓球", value: 3 },
                  ],
                },
                uid: 1718084164279,
              },
              {
                type: "JInput",
                name: "输入框",
                icon: "",
                componentContent: {
                  InputType: "textarea",
                  slotName: "",
                  slotContent: "",
                  suffixIcon: "",
                  prefixIcon: "",
                  maxLength: "100",
                  minLength: "",
                  showWordLimit: true,
                  clearable: true,
                  showPassword: false,
                  resize: "none",
                  rows: 4,
                  variateName: "Info",
                  defaultValue: "",
                  width: "",
                  size: "",
                  label: "个人简介：",
                  labelWidth: 0,
                  labelPosition: "left",
                  placeholder: "请输入个人简介",
                  prop: "",
                  isRequired: false,
                  disabled: false,
                  verifyMsg: "",
                  isCustomVerify: false,
                  customVerify: "",
                },
                uid: 1718084166199,
              },
            ],
          },
        },
      ],
      deviceType:1
    };
  },
  getters: {},
  actions: {
    setDeviceType(type:number){
      this.deviceType = type;
    },
    setAppData(item){
      this.AppData = item.tempInfo;
    },
    delAppData(){
      this.AppData = {
        size: "default",
        labelPosition: "left",
        labelWidth: 0,
        formName: "formSetting",
        RefFormName: "formRef",
        rulesName: "rules",
        AppList: [],
      };
    },
    setCurrentComponent(uid) {
      this.currentComponent = this.AppData.AppList.find((e) => e.uid == uid);
    },
    delCurrentComponent(index) {
      return new Promise((resolve,reject)=>{
         this.AppData.AppList.splice(index, 1);
         if(this.AppData.AppList.length){
          resolve(this.AppData.AppList.at(-1).uid);
         }else{
          reject()
         }
      })
    },
  },
  // persist: {
  //   enabled: true,
  //   strategies: [
  //     { storage: localStorage }, // userInfo localstorage存储
  //   ],
  // },
});
